### ISSUE TITLE
Unable to set "description" for an archive

### ISSUE THREAD

**Issue by BenKennish** [vsespb/mt-aws-glacier#119]
Is it possible to manually set the "description" for archives that are uploaded to a Glacier vault with this tool?  

With a test upload using this tool, the description was set to "mt2 eyJmaWxlbmFtZSI6ImFwcDIuZGMuZnVicmEubmV0LnRhci5neiIsIm10aW1lIjoiMjAxNjA5MDZUMTYzNDUyWiJ9".   

Relying on the file name set in the local journal is not appropriate for our use case and so we wish to set the archive description to the file name (e.g. "example.tar.gz").

**Comment by vsespb** [comment]
Hello.

> Relying on the file name set in the local journal is not appropriate for our use case

actually it's not set only in local journal, but in both local journal and in the `x-amz-archive-description`. so you can always restore journal from  `x-amz-archive-description`.

Here it is: https://github.com/vsespb/mt-aws-glacier#restoring-journal

Note that it's stored in description not in plaintext, but in special format, described here: https://github.com/vsespb/mt-aws-glacier/blob/master/lib/App/MtAws/MetaData.pm#L42 

Does it help?

**Comment by BenKennish** [comment]
Thank you for clarifying.  However, I am required in my current task to store the description in plaintext so that it can be read by any AWS Glacier tool in the future.  Is there any way I can do this using mtglacier?

**Comment by vsespb** [comment]
Currently no way.

> plaintext so that it can be read by any AWS Glacier tool in the future

You assume that plaintext = any tool can read. Yes, that might be true. AFAIK there was the situation across glacier client "market":
- every tool use own format
- but documents it
- usually it's not plaintext, because plaintext just dont work with special characters in filenames and non-ascii filenames 
- some tools read other tools format but don't advertise which
- yes, some tools read "plaintext"

I've tested one of the tools for windows and it was reading my format ok. but i am not sure ;)
