### ISSUE TITLE
Vault management

### ISSUE THREAD

**Issue by funjon** [vsespb/mt-aws-glacier#15]
When are you planning to add support for vault management (create/delete)?

currently I'm using mt-aws-glacier to archive large backups and logs, and eventually I want to have vaults created by calendar month, to ease rotation and purge management.  Otherwise, this is pretty epic, thanks :)

**Comment by vsespb** [comment]
Hello.

Yes I am planning to add it this month.

Initially I considered vault management as a secondary feature,
because it's better for user to set up vaults and Amazon IAM keys with limited permission manually, and not store keys with permission to delete archives on a server which makes backup, in this case backup will be protected in case server compromised)

But of course backup rotation is pretty typical case..

btw Currently you can use 1 vault and different journal files (one for one month) with same scheme. But in this case you must backup journal files .

I will get back to you when release this feature.

**Comment by vsespb** [comment]
Implemented in v0.85beta , see readme for details.
