### ISSUE TITLE
Following symoblic links

### ISSUE THREAD

**Issue by monofonik** [vsespb/mt-aws-glacier#38]
Hi, this tool is great. Is there a reason why it doesn't follow symbolic links on the local filesystem? I'd like to have a "glacier" folder that contains links to large directories on various file systems, and back them all up as one job.

**Comment by vsespb** [comment]
Hello. Thanks.

Well, I can add this option in the future, but there will be some problems with edge cases
1. performance problems (because of protection from cyclic links, see http://search.cpan.org/perldoc?File%3A%3AFind "follow" documentation )
2. when downloading large files, temporary files are used (without performance penalty, i.e. renamed in the end to original files). so those files should be in same directory as
   target file. and they are, now. but I am going to add option to override temp directory, and obviously it will conflict with symlink following, because files from different filesystems can't be moved without copying it.
3. case-sensetivity/unicode normalization detection for MacOSX/ZFS should be implemented in the future. This will work only on one partition, or partitions should be detected.

Also I am going to add option "basedir". It will allow you to map files from different places to different parts of journal.
i.e
with `--dir /home/photos --basedir myphotos`, file `/home/photos/abc/def.jpeg` will map to `myphotos/abc/def.jpeg` in journal
and
with `--dir /data/backups --basedir mybackups`, file `/data/backups/xyz/f.gz` will map to `mybackups/xyz/f.jpeg` in journal

You  will have to run two sync jobs, one for each directory. But at least it will work with same journal/vault.

I will leave this ticket open and let you know when something is implemented.

**Comment by monofonik** [comment]
Thanks for the quick reply - yeah I see what you mean, symlinks will add a few complexities to the process.

**Comment by vsespb** [comment]
Ok, done in `v0.973`, works only when `--follow` option is specified. Documentation updated.
