### ISSUE TITLE
How to get Inventory Last Updated

### ISSUE THREAD

**Issue by cgfrosty** [vsespb/mt-aws-glacier#46]
Hello,

Problem
We need to know what our glacier backup doing every day.
We use PRTG for monitoring our IT infrastructure. Unfortunately it does not have sensor for glacier. But we can create custom sensor and read test files in linux machine with mt-aws-glacier.
Question
Is it possible to get "Inventory Last Updated" from glacier service side via mt-aws-glacier and write it to text file in local machine?
If it is possible it make us very happy!
Thank you!
Alex

**Comment by vsespb** [comment]
Hi.  `retrieve-inventory` command + `download-inventroy` (wait 4h between them). It will write Journal file. It's a text file, but format is custom, not really documented and can change.

**Comment by vsespb** [comment]
How exactly you were going to parse the text file? I might help you with regexps and advice about future compatibility issues. 

There are some docs about journal format https://github.com/vsespb/mt-aws-glacier#journal-concept but it does not define exact format.

Also, you can `check-local-hash` with journal. It will check that all your files (defined in journal) are in place and checksum does match and will return error code otherwise. (that's probably exactly what you want, but error will be thrown if just few existing files are already modified but not yet backuped, and that can be a problem)

**Comment by vsespb** [comment]
closing for now, let me know if you have further questions - I will reopen then.
