### ISSUE TITLE
Question: charset in filenames

### ISSUE THREAD

**Issue by phonoarchive** [vsespb/mt-aws-glacier#51]
Добрый день, Виктор! Прошу извинения, если что-то аглицки напишу не так -- пиетет к англоязычному сообществу требует написания вопроса на этом языке...

Dear Victor,

Could you give me an advice concerning the filenames I want to sync: how can I use characters like & « » Æ and so on? Every time I get this message:  
Invalid octets in filename, does not map to desired encoding "UTF-8". But when I type
locale | egrep "LANG=" | cut -d . -f 2
it shows UTF-8. I use Debian GNU/Linux 5.0.

Thanks in advance,
Nikita

**Comment by vsespb** [comment]
hi. your locale is UTF-8 indeed. Problem that your filenames are not in UTF-8 (that can be so). If you see it correctly in virtual terminal, that means your virtual terminal is not UTF-8.

how to check this:
1. create a text file with UTF-8 _content_ (not filename).
2. `cat thisfile`

if you see characters correctly then your virtual terminal is in UTF-8 mode

next,
1. ls -la /path/to/yourfiles

if you see filenames correctly that it's in UTF-8 too.

I assume you'll fail this check? (that means you filenames are not in UTF-8)

then you'll need realize why it's not in UTF-8.

If you want to keep it in that encoding (probably it's Latin1), you can use `--filename-encoding` option (more info here https://github.com/vsespb/mt-aws-glacier#configuring-character-encodings )

If you want to fix encdonig you can use `convmv` tool (described here too https://github.com/vsespb/mt-aws-glacier#configuring-character-encodings )

All files `mtglacier` works on should be in same encoding (defined via `--filename-encoding` which defaults to UTF-8).

**Comment by phonoarchive** [comment]
Thank you very much! --filename-encoding works great! Allow me to add another little question: when I upload something like /home/music/Bach to Glacier, can I expect, that when I'll retrieve my files back, the name of initial folder "Bach" will be restored? Or, all files will be uploaded without any reference to "Bach"?

**Comment by vsespb** [comment]
> can I expect, that when I'll retrieve my files back, the name of initial folder "Bach" will be restored?

It will store relative filename to transfer root (i.e. `--dir`)

it's documented here https://github.com/vsespb/mt-aws-glacier#what-is-journal

so,

`--dir  /home/music/Bach` won't store "Batch"
`--dir  /home/music/` will store "Batch/..." but will backup everything in /home/music/
`--dir  /home/` will store "music/Batch/..." but will backup everything in /home/

to wrokaround:

`--dir  /home/music/ --filter "+/Batch/ -"` will store "Batch/..." and backup only /home/music/Batch
`--dir  /home/ --filter "+/music/Batch/ -"` will store "Batch/..." and backup only /home/music/Batch

`--filter` option documented here https://github.com/vsespb/mt-aws-glacier#file-selection-options
(note that /music/Batch looks like absolute filename, but it's relative in `filter` it's by design and documented)

it's recommended to use `--dry-run` to test `filter` options

note that
`--dir  /home/ --filter "+/music/Batch/ -"`
can be slow if yo have other huge directories in /home (or will warn/crash if you have permission denied somewhere in /home/)

to workaround exclude it before including music/Batch:

`--dir  /home/ --filter "- /somehugedir/ -/anotherhugedir/ +/music/Batch/ -"`

this is documented as:

```
5) In some cases, to reduce disk IO, directory traversal into excluded directory can be stopped. This only can happen when mtglacier absolutely sure that it won't break behavior (4) described above. Currently it's guaranteed that traversal stop only in case when:

A directory match EXCLUDE rule without '!' prefix, ending with '/' or '**', or empty rule

AND there are no INCLUDE rules before this EXCLUDE RULE
```

in the future I am going to add option (something like `--basedir`) to contral relativeness of filenames with ease.

**Comment by phonoarchive** [comment]
OK, got it! And the last question: how can I delete individual files from vault? I didn't find any explanation (only --pruge-vault option, but it will delete everything?)

**Comment by vsespb** [comment]
Yep, there is no strict specifications for `purge-vault` command but you can use it with file selection options:

https://github.com/vsespb/mt-aws-glacier#file-selection-options

```
filter, include, exclude options allow you to construct a list of RULES to select only certain files for the operation. Can be used with commands: sync, purge-vault, restore, restore-completed and check-local-hash
```

try with `--dry-run` first you see if it works for you.

**Comment by phonoarchive** [comment]
Perfect! Many thanks to you again, Victor!
