### ISSUE TITLE
path to config file

### ISSUE THREAD

**Issue by korjavin** [vsespb/mt-aws-glacier#59]
$ ls -lah ~/.glacier.cfg  
-rw-r--r-- 1 user group 32 дек 12 21:20 /home/..../.glacier.cfg

$ ./mtglacier sync --config=~/.glacier.cfg

ERROR: Config file is not a file: "~/.glacier.cfg"

**Comment by vsespb** [comment]
hi. why it's `32 дек 12 21:20` (32 December) ?

**Comment by korjavin** [comment]
32 bytes, дек 12

**Comment by vsespb** [comment]
ok, indeed.

```
./mtglacier --config=~/.glacier.cfg
```

does not work. because string `--config=~/.glacier.cfg` is passed by shell to `mtglacier`

and

```
./mtglacier --config ~/.glacier.cfg
```

works, becasue `'--config' = '/home/USERNAME/.glacier.cfg'` passed to `mtglacier`

i.e. expanding tilde is your shell work.

I think there are rules explained http://www.gnu.org/software/bash/manual/html_node/Tilde-Expansion.html

so I am closing this as not-a-bug. let me know if you still think it should be fixed somehow.

p.s.
and also you can try using `$HOME` as workaround.

**Comment by korjavin** [comment]
Fine!
Thank you!
