### ISSUE TITLE
Restore to different location

### ISSUE THREAD

**Issue by hauensteina** [vsespb/mt-aws-glacier#69]
Suppose I back up using
mtglacier --dir /var/www

Suppose I want to restore to a different location, e.g
/restored/var/www

How would I do that ?

thanks for writing this great tool,

-Andreas

**Comment by vsespb** [comment]
hi.
restore with `mtglacier --dir /restored/var/www`

there are no absolute paths inside mtglacier data (Journal file nor Amazon Glacier servers metadata). 
the only thing stored in Journal is relative filenames (relative to `--dir`)
So if you change `--dir` mtglacier won't see difference.

**Comment by hauensteina** [comment]
Thank you !

Will try.

-Andreas

**Comment by hauensteina** [comment]
If I have to backups to the same vault:
mtglacier --dir /var/www
mtglacier --dir /home

Then I restore that vault to another location:

mtglacier --dir /restore/everything

What happens ?

-Andreas

**Comment by vsespb** [comment]
If you've used same journal+vault for both `/var/www` and `/home` then `/home/abc` stored as `abc` and `/var/www/def` stored as `def`, thus if you restore to `/restore/everything` yo'll have `/restore/everything/abc` and `/restore/everything/def`

in general it's better to use different journal+vault for different locations otherwise `/var/www/abc` and `/home/abc` map to same file.

**Comment by hauensteina** [comment]
Very helpful, thank you for the quick reply.
Will use different vaults.

-Andreas

**Comment by vsespb** [comment]
ok, cool.
