### ISSUE TITLE
How to see retrieval job status?

### ISSUE THREAD

**Issue by betjaminrichards** [vsespb/mt-aws-glacier#71]
Is there anyway to see the output of the current job list? I can't find it in the documentation.

**Comment by vsespb** [comment]
Hello.

There is no way.

What's the use case to see job list? Currently you can just run `restore-completed` command and it will download files which are ready or do nothing if none are ready. So you can run `restore-completed` several times until everything is downloaded.

**Comment by betjaminrichards** [comment]
I suppose it's just to check that the job has been successfully scheduled and is running, similar to the information you get from the API here:

http://docs.aws.amazon.com/amazonglacier/latest/dev/api-jobs-get.html

**Comment by vsespb** [comment]
> I suppose it's just to check that the job has been successfully scheduled and is running

if `mtglacier` terminated successfully after restore, that means all files to be restores should be restored. Any API error code (HTTP 500, HTTP 400) is checked. Errored requests retried or `mtglacier` terminated with error (depending on type of error). (otherwise that would be a bug in `mtglacier`)

I don't see a possibility in Amazon Glacier API to return success code but not to schedule the job. (if it does, that's error on Amazon side). Well, that's probably impossible as initiate job request should return job id.

> similar to the information you get from the API here

there will be low-level commands some day, including listing of job statuses, but this will be low level interface, not related to "Journal" and files in system.
