### ISSUE TITLE
Question about overriding the config and pausing uploads 

### ISSUE THREAD

**Issue by michae1ho11ey** [vsespb/mt-aws-glacier#82]
Thanks for putting together such a great tool! In setting up this tool at my company for occasional backups I had a few questions that I didn't find explicitly noted anywhere.
1. If I specify a variable, like journal, in the config file, can that variable be overridden if I specify a different journal name on the command line?
2. Is there a way to pause/stop an upload then pick it up where I left off at a later time?

**Comment by vsespb** [comment]
1. yes of course command line overrides config and it was always so. I have unit tests for this to ensure it works that way and always will be. but unfortunately I forgot to document that. Now fixed in README https://github.com/vsespb/mt-aws-glacier/commit/7336eef9422710b87c0719cd3a01f73f8631e177.
2. try Ctrl-S / Ctlr-Q in linux. This suspend processes. I think I tested it and it was working. However amazon upload ids are valid for 24hours. Also I think if you unfreeze the process current uploading will break and mtglacier will re-upload part (just **one part** for each worker (`--concurrency`), not **one file**). Also there was a feature request to allow continue uploading #62 of a file after process exit. Also, of course, if you upload large **set of files**, and terminate process, it will continue from same place, at maximum yo'll loose time of uploading **one file** or several files (one for each worker).
